export const carList = [
    {
        id: 1,
        name: "Sports GTI",
        image: "3d_car/cars-list/Sports_GTI.png",
        fileUrl: "3d_car/gltf_file/car14_F-Sports_GTI-S.gltf",
        posterURL: "3d_car/poster/F-Sports_GTI-S.webp",
        class: "s",
    },
    {
        id: 2,
        name: "Specter",
        image: "3d_car/cars-list/Specter.png",
        fileUrl: "3d_car/gltf_file/car12_F-Specter-S.gltf",
        posterURL: "3d_car/poster/F-Specter-S.webp",
        class: "s",
    },
    {
        id: 3,
        name: "Dominator",
        image: "3d_car/cars-list/Dominator.png",
        fileUrl: "3d_car/gltf_file/car07_Dominator-S.gltf",
        posterURL: "3d_car/poster/Dominator-S.webp",
        class: "s",
    },
    {
        id: 4,
        name: "Osiris",
        image: "3d_car/cars-list/Osiris.png",
        fileUrl: "3d_car/gltf_file/car19_Osiris-S.gltf",
        posterURL: "3d_car/poster/Osiris-S.webp",
        class: "s",
    },
    {
        id: 5,
        name: "Rhino V8",
        image: "3d_car/cars-list/Rhino_V8.png",
        fileUrl: "3d_car/gltf_file/car20_Rhino_V8-S.gltf",
        posterURL: "3d_car/poster/Rhino_V8-S.webp",
        class: "s",
    },
    {
        id: 6,
        name: "Tyrus",
        image: "3d_car/cars-list/Tyrus.png",
        fileUrl: "3d_car/gltf_file/car30_Tyrus-S.gltf",
        posterURL: "3d_car/poster/Tyrus-S.webp",
        class: "s",
    },
    {
        id: 7,
        name: "Bullet Turbo",
        image: "3d_car/cars-list/Bullet Turbo.png",
        fileUrl: "3d_car/gltf_file/car29_Bullet_Turbo-A.gltf",
        posterURL: "3d_car/poster/Bullet_Turbo-A.webp",
        class: "a",
    },
    {
        id: 8,
        name: "Jester",
        image: "3d_car/cars-list/Jester.png",
        fileUrl: "3d_car/gltf_file/car31_Jester-A.gltf",
        posterURL: "3d_car/poster/Jester-A.webp",
        class: "a",
    },
    {
        id: 9,
        name: "Aruma",
        image: "3d_car/cars-list/Aruma.png",
        fileUrl: "3d_car/gltf_file/car05_Aruma-B.gltf",
        posterURL: "3d_car/poster/Aruma-B.webp",
        class: "b",
    },
    {
        id: 10,
        name: "Tornado",
        image: "3d_car/cars-list/Tornado.png",
        fileUrl: "3d_car/gltf_file/car27_Tornado-B.gltf",
        posterURL: "3d_car/poster/Tornado-B.webp",
        class: "b",
    },
    {
        id: 11,
        name: "Sports Turbo",
        image: "3d_car/cars-list/Sports Turbo.png",
        fileUrl: "3d_car/gltf_file/car10_F-Sport_Turbo-C.gltf",
        posterURL: "3d_car/poster/F-Sport_Turbo-C.webp",
        class: "c",
    },
    {
        id: 12,
        name: "T5 Classic",
        image: "3d_car/cars-list/T5_Classic.png",
        fileUrl: "3d_car/gltf_file/car11_T5_Classic-C.gltf",
        posterURL: "3d_car/poster/T5_Classic-C.webp",
        class: "c",
    },
    {
        id: 13,
        name: "Buffalo Classic",
        image: "3d_car/cars-list/Buffalo_Classic.png",
        fileUrl: "3d_car/gltf_file/car16_Buffalo_classic-D.gltf",
        posterURL: "3d_car/poster/Buffalo_classic-D.webp",
        class: "d",
    },
    {
        id: 14,
        name: "Coquette GTO",
        image: "3d_car/cars-list/Coquette GTO.png",
        fileUrl: "3d_car/gltf_file/car21_Coquette_GTO-D.gltf",
        posterURL: "3d_car/poster/Coquette_GTO-D.webp",
        class: "d",
    },
];